# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: shaunco/ssh-agent@git-repo-mapping 
      with:
        ssh-private-key: ${{ secrets.EXPECT_SSH_PRIVATE_KEY }}
        repo-mappings: https://github.com/Dimension-North-Inc/Expect.git
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
